telegram-bot:
  token: 738271206:AAFkVt7Bht1Fr8FmN7PC3hD68FnLxLaM03g
  name: JiraNotificationBot

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/liquibase-changeLog.xml
